spring:
  application:
    name: books
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookstore
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true